### ISSUE TITLE
Why do Roles have multiple parents?

### ISSUE THREAD

**Issue by dennis-fedco** [coolcsn/CsnUser#2]
Just wondering -- what is the purpose for having multiple parents for a role?
Do you have an example?

Thanks

**Comment by coolcsn** [comment]
Hello Dennis,
Yes, the ACL roles can have multiple parents. Example:
You have 
"public"
"prospect"
"member"
"admin"

In order to allow the "admin" to do everything what the "prospect" and the "member" do, you have to inherit both roles. Let me go ahead and tell you that the situation with the resources is the same. There is multiple inheritance with the resources as well. B.T.W. Join us in our IRC channel "#coolcsn" on http://freenode.net/. You can talk directly with the developers.
